INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Davi Gomes Machado', 'davi.machado@hotmail.com')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Rafaela Amaral Teixeira', 'rafaela.teixeira@hotmail.com')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Davi Ducati Gomes', 'davi.gomes@gmail.com')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Lucas Amaral Gomes', 'lucas.gomes@gmail.com')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Gabriel Amaral Teixeira', 'gabriel.teixeira@uol.com.br')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Lara Teixeira Amaral', 'lara.amaral@yahoo.com')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Mariana Amaral Gomes', 'mariana.gomes@hotmail.com')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Laura Amaral Gomes', 'Laura Amaral Gomes')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Carlos Teixeira Gomes', 'carlos.gomes@gmail.com')
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Gabriela Gomes Amaral', 'gabriela.amaral@hotmail.com')