INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Tv LG','1.500');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Som','850,00');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Fogão','450,00');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Notebook','2.500');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Smartphone','1.250');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Xiaomi Hifi Sound ','129,88');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Parafusadeira e Furadeira Philco','139,99');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Servidor HPE ISS Microserver Gen10','2.300');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Notebook Gamer Aspire AN515-51-50U2','3.778,26');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Camera Digital 720p 16x Zoom','145,92');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Roteador Dell','849,99');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Câmera Externa De Segurança Wi-fi Full Hd Com Infravermelho','499,90');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Roteador Wireless N 300mbps Iwr 3000n','74,99');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Roteador Mesh Twibi Giga','469,99');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Lf606 Mini Drone Com Câmera','100,62');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Xb950 Bluetooth Fone De Ouvido','104,14');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Sweatproof Smarcent X9 De Metal Bluetooth','155,54');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Geladeira/Refrigerador 500L - Inox','3.129,99');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Microondas Lg Ms3059La 30L','435,53');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Smart TV LED 40" Samsung Ultra HD','1.665,02');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Lavadora de Roupas Brastemp 11kg ','1.448,99');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Kit Ferramentas Sparta 129 Peças','69,90');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Lavadora de alta pressão 2.000 libras','1.288,00');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Kit Premium Wine Philco com Liquidificador','294,41');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Pneu Aro 14” Firestone 175/65R14','312,00');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Churrasqueira à Carvão','94,91');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Caixa de Som Bluetooth JBL','389,00');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Impressora Multifuncional','314,91');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Guarda-roupa Casal ','552,95');
INSERT INTO produtos (DESCRICAO, PRECO) VALUES ('Aparelho de Barbear','98,90');
