FROM postgres
ENV POSTGRES_DB dac_jms
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
#COPY insert_clientes.sql /docker-entrypoint-initdb.d/
#COPY insert_produtos.sql /docker-entrypoint-initdb.d/
